### ISSUE TITLE
Use PDC when Bodhi is unavailable

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/fedora-distro-aliases#12]
We can utilize:
https://pdc.fedoraproject.org/rest_api/v1/product-versions/?active=true

There is a library to interact with PDC
https://packages.fedoraproject.org/pkgs/pdc-client/python3-pdc-client/index.html

Related to #11

**Comment by FrostyX** [comment]
I don't know the ETA but there are plans to kill the PDC
https://communityblog.fedoraproject.org/2023-year-in-review-cpe/

> PDC Retirement
> PDC is the Product Definition Center, running at: https://pdc.fedoraproject.org/.
>
> However, this application which was developed internally, is no longer maintained. This codebase has been “orphaned” for a few years now and we need to find a solution for it.
>
> We are reviewing and having a critical look on what we store in there, see what is really needed and then find a solution for its replacement.

**Comment by xsuchy** [comment]
I contacted @zlopez and we indeed should not use PDC. 
He pointed me to https://mdapi.fedoraproject.org/ as another alternative. But that have only subset of information.
