### ISSUE TITLE
The latest version on PyPI is 1.2

### ISSUE THREAD

**Issue by nforro** [rpm-software-management/fedora-distro-aliases#23]
https://pypi.org/project/fedora-distro-aliases/#history

**Comment by FrostyX** [comment]
Thank you @nforro,
I uploaded all the missing versions https://pypi.org/project/fedora-distro-aliases/#history

**Comment by nforro** [comment]
You can use a Github Action to do it automatically on release:
https://github.com/packit/packit/blob/e7265a906c88939971c77b2e2ef7d062557f8ea9/.github/workflows/pypi-publish.yml
