### ISSUE TITLE
add attribute version_number

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/fedora-distro-aliases#9]
I want to add new attribute to release dict that would be name `version_number`. It would be the same as `version` except for rawhide there was the number. I.e. currently 41 instead of `rawhide`.

My motivation is to use it in situation like this https://github.com/rpm-software-management/mock/pull/1342 where we need to know version of current rawhide to map it to current gpg key.

If you are ok with the name of the attribute I will create a PR.

**Comment by praiskup** [comment]
I'm curious whether issue #4 or similar wouldn't affect mock if used like this?
I'm also a bit afraid of Bodhi API outages causing mock/copr builds to fail.

**Comment by FrostyX** [comment]
> I want to add new attribute to release dict that would be name version_number. It would be the same as version except for rawhide there was the number. I.e. currently 41 instead of rawhide.

This is trivial to do

```diff
--- a/fedora_distro_aliases/__init__.py
+++ b/fedora_distro_aliases/__init__.py
@@ -79,7 +79,9 @@ class Distro(Munch):
         Create a `Distro` object from Bodhi `release`
         """
         keys = ["name", "long_name", "version", "state", "branch", "id_prefix"]
-        return cls({k: getattr(release, k) for k in keys})
+        distro = cls({k: getattr(release, k) for k in keys})
+        distro.version_number = distro.version
+        return distro

     @property
     def product(self):
```

I can send a PR right now.

However ... having the version as a number for rawhide was the default, we _intentionally_ changed the number to "rawhide"

```python
# The Fedora with the highest version is "rawhide", but
# Bodhi always uses release names, and has no concept of "rawhide".
fedora[-1].update({
    "name": "Rawhide",
    "long_name": "Fedora Rawhide",
    "version": "rawhide",
    "branch": "rawhide",
})
```

Hopefully that wasn't a mistake. If it was, we can probably still change it. But we would need to figure out another way to generate Mock chroot names.
